export const journalPrompts = [
  "What unnecessary things am I holding onto today?",
  "How can I show gratitude to those who shaped me?",
  "What virtues did I practice yesterday, and which ones need attention today?",
  "What anxieties about the future are preventing me from acting now?",
  "How am I standing in my own way today?",
  "What difficult conversation am I avoiding?",
  "What would my wisest self do in my current situation?",
  "How can I turn today's obstacles into opportunities?",
  "What negative thoughts am I harboring that I need to release?",
  "How can I better serve others today?",
  "What truth am I refusing to accept?",
  "How can I practice courage in small ways today?",
  "What habits are holding me back from growth?",
  "How am I letting external events control my peace?",
  "What lessons can I learn from yesterday's mistakes?",
  "How can I show more patience today?",
  "What assumptions am I making without evidence?",
  "How can I be more present in my daily activities?",
  "What small act of kindness can I perform today?",
  "How am I preparing for potential challenges ahead?",
  "What principles am I compromising for convenience?",
  "How can I better align my actions with my values?",
  "What unnecessary suffering am I creating through judgment?",
  "How can I practice temperance today?",
  "What wisdom from my experiences can I apply today?",
  "How am I contributing to the problems I complain about?",
  "What aspects of my character need strengthening?",
  "How can I be more honest with myself?",
  "What responsibilities am I avoiding?",
  "How can I maintain tranquility amid today's challenges?",
  "What prejudices are clouding my judgment?",
  // February
  "What legacy am I building with today's actions?",
  "How can I embrace discomfort for growth?",
  "What relationships need more attention from me?",
  "How am I practicing self-discipline today?",
  "What false narratives am I telling myself?",
  "How can I reduce complexity in my life?",
  "What knowledge am I seeking to improve myself?",
  "How am I responding to things outside my control?",
  "What boundaries do I need to establish or maintain?",
  "How can I lead by example today?",
  "What excuses am I making for poor choices?",
  "How can I show more compassion to others and myself?",
  "What unnecessary conflicts am I engaging in?",
  "How can I cultivate more wisdom in my daily life?",
  "What fears are preventing my growth?",
  "How can I practice humility today?",
  "What distractions are stealing my focus?",
  "How can I be more resilient in facing challenges?",
  "What grudges do I need to release?",
  "How can I contribute to the greater good today?",
  "What habits can I develop to strengthen my character?",
  "How am I practicing gratitude in difficult times?",
  "What emotional reactions do I need to better control?",
  "How can I be more mindful in my interactions?",
  "What self-imposed limitations can I overcome?",
  "How can I better serve my community?",
  "What virtues am I neglecting?",
  "How can I practice more self-awareness?",

  // March
  "What meaningful work can I accomplish today?",
  "How can I better manage my time and energy?",
  "What negative self-talk do I need to address?",
  "How can I practice more forgiveness?",
  "What opportunities for learning am I missing?",
  "How can I strengthen my mental resilience?",
  "What relationships am I taking for granted?",
  "How can I be more authentic in my actions?",
  "What unnecessary worries can I let go of?",
  "How can I practice more self-discipline?",
  "What wisdom can I share with others today?",
  "How can I be more strategic in my decisions?",
  "What personal biases need examination?",
  "How can I cultivate more inner peace?",
  "What actions align with my highest values?",
  "How can I be more present with loved ones?",
  "What challenges can I reframe as opportunities?",
  "How can I practice more emotional intelligence?",
  "What habits support my long-term goals?",
  "How can I show more empathy to others?",
  "What mental barriers am I creating?",
  "How can I better prepare for future challenges?",
  "What toxic influences should I eliminate?",
  "How can I practice more self-reflection?",
  "What purpose drives my actions today?",
  "How can I be more intentional with my choices?",
  "What wisdom from others can I apply today?",
  "How can I practice more patience with myself?",
  "What positive changes can I initiate?",
  "How can I be more mindful of my impact on others?",
  "What steps can I take toward personal growth?",

  // April
  "What creative solutions can I find to today's problems?",
  "How can I better honor my commitments?",
  "What limiting beliefs should I challenge today?",
  "How can I practice more stoic acceptance?",
  "What intellectual pursuits am I neglecting?",
  "How can I improve my decision-making process?",
  "What areas of my life need more balance?",
  "How can I cultivate stronger mental fortitude?",
  "What past experiences can guide me today?",
  "How can I practice better self-governance?",
  "What universal truths am I ignoring?",
  "How can I be more proactive rather than reactive?",
  "What relationships could benefit from more authenticity?",
  "How can I better embody my principles?",
  "What daily practices enhance my character?",
  "How can I cultivate more mental clarity?",
  "What unconscious patterns need examination?",
  "How can I better serve my life's purpose?",
  "What virtuous habits can I strengthen?",
  "How can I practice more emotional equilibrium?",
  "What wisdom am I failing to apply?",
  "How can I be more deliberate in my choices?",
  "What personal standards should I raise?",
  "How can I better regulate my responses?",
  "What philosophical principles can guide me today?",
  "How can I practice more rational thinking?",
  "What character flaws need addressing?",
  "How can I cultivate more inner strength?",
  "What meaningful goals deserve my focus?",
  "How can I practice more mindful living?",

  // May
  "What deeper understanding am I seeking today?",
  "How can I better handle life's uncertainties?",
  "What personal truths need defending?",
  "How can I practice more ethical living?",
  "What spiritual growth am I neglecting?",
  "How can I better serve truth and justice?",
  "What worldly attachments should I loosen?",
  "How can I practice more rational judgment?",
  "What higher principles guide my choices?",
  "How can I cultivate more mental discipline?",
  "What universal laws am I resisting?",
  "How can I better align with nature's wisdom?",
  "What personal power am I not claiming?",
  "How can I practice more philosophical thinking?",
  "What deeper questions should I be asking?",
  "How can I cultivate more inner wisdom?",
  "What eternal truths need remembering?",
  "How can I practice more virtuous living?",
  "What moral excellence can I pursue today?",
  "How can I better understand human nature?",
  "What cosmic perspective am I missing?",
  "How can I practice more rational acceptance?",
  "What universal principles need attention?",
  "How can I better serve the common good?",
  "What timeless wisdom can guide me today?",
  "How can I practice more philosophical acceptance?",
  "What higher understanding am I seeking?",
  "How can I better embody wisdom?",
  "What eternal principles guide my path?",
  "How can I practice more contemplative living?",
  "What deeper truths await my discovery?",

  // June
  "What ancient wisdom can I apply to modern challenges?",
  "How can I develop more mental toughness?",
  "What societal conditioning should I question?",
  "How can I practice more detachment from outcomes?",
  "What inherited beliefs need reassessment?",
  "How can I cultivate more intellectual humility?",
  "What fundamental truths guide my existence?",
  "How can I practice more strategic patience?",
  "What core values need strengthening?",
  "How can I better understand opposing viewpoints?",
  "What philosophical insights can guide my decisions?",
  "How can I practice more emotional maturity?",
  "What deeper patterns shape my behavior?",
  "How can I cultivate more practical wisdom?",
  "What essential principles am I overlooking?",
  "How can I practice more mindful leadership?",
  "What foundational habits need attention?",
  "How can I better serve universal truth?",
  "What primal fears need addressing?",
  "How can I practice more rational detachment?",
  "What eternal questions deserve contemplation?",
  "How can I better understand my true nature?",
  "What fundamental changes are needed?",
  "How can I practice more strategic thinking?",
  "What core strengths need development?",
  "How can I better align with universal laws?",
  "What essential wisdom am I ignoring?",
  "How can I practice more conscious living?",
  "What deeper purpose guides my journey?",
  "How can I better serve humanity's progress?",

  // July
  "What ancient principles need modern application?",
  "How can I develop more mental sovereignty?",
  "What cultural assumptions need challenging?",
  "How can I practice more philosophical detachment?",
  "What inherited patterns need transformation?",
  "How can I cultivate more intellectual rigor?",
  "What foundational truths anchor my life?",
  "How can I practice more strategic wisdom?",
  "What core beliefs need examination?",
  "How can I better understand human motivation?",
  "What philosophical traditions offer guidance?",
  "How can I practice more emotional wisdom?",
  "What deeper currents shape my choices?",
  "How can I cultivate more practical insight?",
  "What essential truths guide my path?",
  "How can I practice more mindful influence?",
  "What fundamental practices need attention?",
  "How can I better serve collective wisdom?",
  "What primal instincts need mastery?",
  "How can I practice more rational observation?",
  "What timeless questions deserve reflection?",
  "How can I better understand collective consciousness?",
  "What fundamental shifts are necessary?",
  "How can I practice more strategic awareness?",
  "What core capacities need strengthening?",
  "How can I better align with natural laws?",
  "What essential insights am I missing?",
  "How can I practice more conscious evolution?",
  "What deeper calling guides my path?",
  "How can I better serve humanity's evolution?",
  "What ancient wisdom needs preservation?",
  // August
  "What sacred principles deserve protection?",
  "How can I develop more cognitive flexibility?",
  "What generational wisdom needs preservation?",
  "How can I practice more philosophical courage?",
  "What ancestral knowledge guides my path?",
  "How can I cultivate more dialectical thinking?",
  "What metaphysical truths shape reality?",
  "How can I practice more contemplative inquiry?",
  "What primordial wisdom needs revival?",
  "How can I better understand collective healing?",
  "What perennial philosophy offers insight?",
  "How can I practice more conscious leadership?",
  "What archetypal patterns guide growth?",
  "How can I cultivate more sacred awareness?",
  "What eternal principles need honoring?",
  "How can I practice more mindful stewardship?",
  "What foundational virtues need cultivation?",
  "How can I better serve evolutionary purpose?",
  "What instinctual wisdom needs integration?",
  "How can I practice more philosophical rigor?",
  "What timeless teachings need application?",
  "How can I better understand divine nature?",
  "What fundamental truths need expression?",
  "How can I practice more strategic virtue?",
  "What core wisdom needs embodiment?",
  "How can I better align with cosmic order?",
  "What essential knowledge needs sharing?",
  "How can I practice more enlightened living?",
  "What deeper mysteries guide existence?",
  "How can I better serve universal harmony?",
  "What ancient traditions need honoring?",

  // September
  "What transcendent principles guide wisdom?",
  "How can I develop more philosophical depth?",
  "What eternal questions need exploration?",
  "How can I practice more conscious evolution?",
  "What timeless patterns shape growth?",
  "How can I cultivate more sacred understanding?",
  "What fundamental laws govern reality?",
  "How can I practice more mindful inquiry?",
  "What core teachings need integration?",
  "How can I better understand divine wisdom?",
  "What philosophical heritage offers guidance?",
  "How can I practice more conscious awareness?",
  "What deeper patterns shape evolution?",
  "How can I cultivate more spiritual insight?",
  "What essential principles need embodiment?",
  "How can I practice more mindful service?",
  "What foundational wisdom needs attention?",
  "How can I better serve universal truth?",
  "What primal knowledge needs awakening?",
  "How can I practice more philosophical depth?",
  "What eternal wisdom needs preservation?",
  "How can I better understand cosmic order?",
  "What fundamental insights need sharing?",
  "How can I practice more strategic wisdom?",
  "What core principles need application?",
  "How can I better align with divine law?",
  "What essential truth needs expression?",
  "How can I practice more conscious being?",
  "What deeper purpose guides existence?",
  "How can I better serve cosmic evolution?",
  // October
  "What mystical wisdom awaits discovery?",
  "How can I develop more spiritual discernment?",
  "What universal patterns need recognition?",
  "How can I practice more sacred observation?",
  "What hidden knowledge seeks expression?",
  "How can I cultivate more divine awareness?",
  "What cosmic laws shape consciousness?",
  "How can I practice more enlightened thinking?",
  "What eternal mysteries need exploration?",
  "How can I better understand universal consciousness?",
  "What spiritual traditions offer guidance?",
  "How can I practice more transcendent living?",
  "What divine patterns shape evolution?",
  "How can I cultivate more cosmic understanding?",
  "What sacred principles need embodiment?",
  "How can I practice more universal service?",
  "What celestial wisdom needs attention?",
  "How can I better serve divine purpose?",
  "What immortal knowledge needs awakening?",
  "How can I practice more spiritual depth?",
  "What infinite wisdom needs preservation?",
  "How can I better understand eternal order?",
  "What transcendental insights need sharing?",
  "How can I practice more divine wisdom?",
  "What supreme principles need application?",
  "How can I better align with infinite law?",
  "What ultimate truth needs expression?",
  "How can I practice more enlightened being?",
  "What higher purpose guides creation?",
  "How can I better serve divine evolution?",
  "What mystic traditions need honoring?",

  // November
  "What ethereal principles guide transformation?",
  "How can I develop more spiritual sovereignty?",
  "What universal questions need contemplation?",
  "How can I practice more divine detachment?",
  "What cosmic patterns need integration?",
  "How can I cultivate more sacred rigor?",
  "What eternal truths anchor existence?",
  "How can I practice more transcendent wisdom?",
  "What divine beliefs need examination?",
  "How can I better understand universal motivation?",
  "What spiritual heritage offers insight?",
  "How can I practice more cosmic awareness?",
  "What sacred currents shape destiny?",
  "How can I cultivate more divine insight?",
  "What eternal principles guide evolution?",
  "How can I practice more universal influence?",
  "What transcendent practices need attention?",
  "How can I better serve infinite wisdom?",
  "What divine instincts need mastery?",
  "How can I practice more sacred observation?",
  "What timeless mysteries deserve reflection?",
  "How can I better understand cosmic consciousness?",
  "What eternal shifts are necessary?",
  "How can I practice more divine awareness?",
  "What sacred capacities need strengthening?",
  "How can I better align with cosmic laws?",
  "What transcendent insights need sharing?",
  "How can I practice more universal evolution?",
  "What divine calling guides existence?",
  "How can I better serve eternal harmony?",

  // December
  "What divine wisdom seeks manifestation?",
  "How can I develop more universal awareness?",
  "What celestial patterns need recognition?",
  "How can I practice more mystical observation?",
  "What infinite knowledge seeks expression?",
  "How can I cultivate more transcendent understanding?",
  "What supreme laws shape destiny?",
  "How can I practice more sacred thinking?",
  "What immortal mysteries need contemplation?",
  "How can I better understand spiritual evolution?",
  "What divine traditions offer enlightenment?",
  "How can I practice more cosmic living?",
  "What eternal patterns shape transformation?",
  "How can I cultivate more mystical insight?",
  "What transcendent principles need embodiment?",
  "How can I practice more divine service?",
  "What sacred wisdom needs attention?",
  "How can I better serve spiritual purpose?",
  "What eternal knowledge needs awakening?",
  "How can I practice more universal depth?",
  "What infinite wisdom needs preservation?",
  "How can I better understand sacred order?",
  "What divine insights need sharing?",
  "How can I practice more cosmic wisdom?",
  "What transcendent principles need application?",
  "How can I better align with eternal law?",
  "What sacred truth needs expression?",
  "How can I practice more divine being?",
  "What infinite purpose guides transformation?",
  "How can I better serve eternal evolution?",
  "What mystical traditions need honoring?",
];
